spring:
  cloud:
    stream:
      function.definition: testProcess;testSource;testSink
      bindings:
        testProcess-in-0:
          destination: rest-input,rest-input-error
          group: input-group
          maxAttempts: 1
        testProcess-out-0:
          destination: rest-output
        testSink-in-0:
          destination: rest-output
          group: sink-group
        testSource-out-0:
          destination: rest-input
      kafka:
        bindings:
          testProcess-in-0:
            consumer:
              enableDlq: true
              dlqName: rest-input-error

